In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/DataAwal.csv', encoding='utf-8')

In [3]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,Target
0,0.244898,1,1,0.70,0.479270,0,1,0.788732,0,0.295455,2,0
1,0.428571,0,2,0.80,0.298507,0,1,0.676056,0,0.409091,1,1
2,0.183673,1,1,0.65,0.469320,0,2,0.267606,0,0.295455,2,0
3,0.408163,0,0,0.69,0.354892,0,1,0.338028,1,0.465909,1,1
4,0.530612,1,2,0.75,0.323383,0,1,0.436620,0,0.295455,2,0

In [1]:
from cmath import sqrt

yy = df['Target']
y = df['Target'].sum()
y2 = (df['Target'] * df['Target']).sum()

x_Age = df['Age']
xy_Age = (x_Age * yy).sum()
xAge = df['Age'].sum()
x2_Age = (df['Age'] * df['Age']).sum()

r1_Age = 918 * xy_Age - xAge * y
r2_Age = (918 * x2_Age - (xAge * xAge))
r3_Age = (918 * y2 - (y * y))
r4_Age = sqrt(r2_Age) * sqrt(r3_Age)
r_age = r1_Age / r4_Age
R_age = r_age * r_age

# --------------------------------------------------------------------------
x_sex = df['Sex']
xy_Sex = (x_sex * yy).sum()
xSex = df['Sex'].sum()
x2_Sex = (df['Sex'] * df['Sex']).sum()

r1_Sex = 918 * xy_Sex - xSex * y
r2_Sex = (918 * x2_Sex - (xSex * xSex))
r3_Sex = (918 * y2 - (y * y))
r4_Sex = sqrt(r2_Sex) * sqrt(r3_Sex)
r_Sex = r1_Sex / r4_Sex
R_sex = r_Sex * r_Sex

# -----------------------------------------------------------------------------
x_cpt = df['ChestPainType']
xy_cpt = (x_cpt * yy).sum()
xCPT = df['ChestPainType'].sum()
x2_cpt = (df['ChestPainType'] * df['ChestPainType']).sum()

r1_cpt = 918 * xy_cpt - xCPT * y
r2_cpt = (918 * x2_cpt - (xCPT * xCPT))
r3_cpt = (918 * y2 - (y * y))
r4_cpt = sqrt(r2_cpt) * sqrt(r3_cpt)
r_cpt = r1_cpt / r4_cpt
R_cpt = r_cpt * r_cpt

#------------------------------------------------------------------------------
x_rbp = df['RestingBP']
xy_rbp = (x_rbp * yy).sum()
xRBP = df['RestingBP'].sum()
x2_rbp = (df['RestingBP'] * df['RestingBP']).sum()

r1_rbp = 918 * xy_rbp - xRBP * y
r2_rbp = 918 * x2_rbp - xRBP * xRBP
r3_rbp = 918 * y2 - y * y
r4_rbp = sqrt(r2_rbp) * sqrt(r3_rbp)
r_rbp = r1_rbp / r4_rbp
R_rbp = r_rbp * r_rbp

#-----------------------------------------------------------------------------
x_chl = df['Cholesterol']
xy_chl = (x_chl * yy).sum()
xCHL = df['Cholesterol'].sum()
x2_chl = (df['Cholesterol'] * df['Cholesterol']).sum()

r1_chl = 918 * xy_chl - xCHL * y
r2_chl = 918 * x2_chl - xCHL * xCHL
r3_chl = 918 * y2 - y * y
r4_chl = sqrt(r2_chl) * sqrt(r3_chl)
r_chl = r1_chl / r4_chl
R_chl = r_chl * r_chl

#-----------------------------------------------------------------------------
x_fbs = df['FastingBS']
xy_fbs = (x_fbs * yy).sum()
xFBS = df['FastingBS'].sum()
x2_fbs = (df['FastingBS'] * df['FastingBS']).sum()

r1_fbs = 918 * xy_fbs - xFBS * y
r2_fbs = 918 * x2_fbs - xFBS * xFBS
r3_fbs = 918 * y2 - y * y
r4_fbs = sqrt(r2_fbs) * sqrt(r3_fbs)
r_fbs = r1_fbs / r4_fbs
R_fbs = r_fbs * r_fbs

#-----------------------------------------------------------------------------
x_recg = df['RestingECG']
xy_recg = (x_recg * yy).sum()
xRECG = df['RestingECG'].sum()
x2_recg = (df['RestingECG'] * df['RestingECG']).sum()

r1_recg = 918 * xy_recg - xRECG * y
r2_recg = 918 * x2_recg - xRECG * xRECG
r3_recg = 918 * y2 - y * y
r4_recg = sqrt(r2_recg) * sqrt(r3_recg)
r_recg = r1_recg / r4_recg
R_recg = r_recg * r_recg

#-----------------------------------------------------------------------------
x_mhr = df['MaxHR']
xy_mhr = (x_mhr * yy).sum()
xMaxHR = df['MaxHR'].sum()
x2_mhr = (df['MaxHR'] * df['MaxHR']).sum()

r1_mhr = 918 * xy_mhr - xMaxHR * y
r2_mhr = 918 * x2_mhr - xMaxHR * xMaxHR
r3_mhr = 918 * y2 - y * y
r4_mhr = sqrt(r2_mhr) * sqrt(r3_mhr)
r_mhr = r1_mhr / r4_mhr
R_mhr = r_mhr * r_mhr

#-----------------------------------------------------------------------------
x_ea = df['ExerciseAngina']
xy_ea = (x_ea * yy).sum()
xEA = df['ExerciseAngina'].sum()
x2_ea = (df['ExerciseAngina'] * df['ExerciseAngina']).sum()

r1_ea = 918 * xy_ea - xEA * y
r2_ea = 918 * x2_ea - xEA * xEA
r3_ea = 918 * y2 - y * y
r4_ea = sqrt(r2_ea) * sqrt(r3_ea)
r_ea = r1_ea / r4_ea
R_ea = r_ea * r_ea

#-----------------------------------------------------------------------------
x_op = df['Oldpeak']
xy_op = (x_op * yy).sum()
xOP = df['Oldpeak'].sum()
x2_op = (df['Oldpeak'] * df['Oldpeak']).sum()

r1_op = 918 * xy_op - xOP * y
r2_op = 918 * x2_op - xOP * xOP
r3_op = 918 * y2 - y * y
r4_op = sqrt(r2_op) * sqrt(r3_op)
r_op = r1_op / r4_op
R_op = r_op * r_op

#-----------------------------------------------------------------------------
x_st = df['ST_Slope']
xy_st = (x_st * yy).sum()
xST = df['ST_Slope'].sum()
x2_st = (df['ST_Slope'] * df['ST_Slope']).sum()

r1_st = 918 * xy_st - xST * y
r2_st = 918 * x2_st - xST * xST
r3_st = 918 * y2 - y * y
print(r3_st)
r4_st = sqrt(r2_st) * sqrt(r3_st)
r_st = r1_st / r4_st
R_st = r_st * r_st
#-----------------------------------------------------------
# print("Nilai Korelasi R-Square atribut Age           : ",R_age)
# print("Nilai Korelasi R-Square atribut Sex           : ", R_sex)
# print("Nilai Korelasi R-Square atribut ChestPainType : ", R_cpt)
# print("Nilai Korelasi R-Square atribut RestingBP     : ", R_rbp)
# print("Nilai Korelasi R-Square atribut Cholesterol   : ", R_chl)
# print("Nilai Korelasi R-Square atribut FastingBS     : ", R_fbs)
# print("Nilai Korelasi R-Square atribut RestingECG    : ", R_recg)
# print("Nilai Korelasi R-Square atribut MaxHR         : ", R_mhr)
# print("Nilai Korelasi R-Square atribut ExerciseAngina: ", R_ea)
# print("Nilai Korelasi R-Square atribut Oldpeak       : ", R_op)
# print("Nilai Korelasi R-Square atribut ST_Slope      : ", R_st)
# dt = {'dataage' :R_age, 'datasex' :R_sex, 'datacpt' :R_cpt, 'datarbp' :R_rbp, 'datachl' :R_chl, 'datafbs' :R_fbs, 'datarecg' :R_recg, 'datamhr' :R_mhr, 'dataea' :R_ea, 'dataop' :R_op, 'datast' :R_st}
# print(dt)

NameError: name 'df' is not defined

In [5]:
result_dt = {'Age':R_age, 'Sex':R_sex, 'ChestPainType':R_cpt, 'RestingBP':R_rbp, 'Cholesterol':R_chl, 'FastingBS':R_fbs, 'RestingECG':R_recg, 'MaxHR':R_mhr, 'ExerciseAngina':R_ea, 'Oldpeak':R_op, 'ST_Slope':R_st}

In [6]:
#RSquare
rs_dt = pd.DataFrame(result_dt.items(), columns=['Atribute','Result'])
rs_dt

          Atribute              Result
0              Age  0.079546+0.000000j
1              Sex  0.093297+0.000000j
2    ChestPainType  0.149636-0.000000j
3        RestingBP  0.011575+0.000000j
4      Cholesterol  0.054168-0.000000j
5        FastingBS  0.071445+0.000000j
6       RestingECG  0.003293+0.000000j
7            MaxHR  0.160337-0.000000j
8   ExerciseAngina  0.244315+0.000000j
9          Oldpeak  0.163176+0.000000j
10        ST_Slope  0.312225-0.000000j

In [7]:
data0 = df[df['Target'] == 0]
data_0 = pd.value_counts(data0.Age)
dt = pd.DataFrame(data_0)
dt = dt.reset_index()
dt.columns = ['Age', 'Jumlah']
print(dt)

         Age  Jumlah
0   0.530612      28
1   0.469388      20
2   0.265306      18
3   0.510204      18
4   0.489796      17
5   0.551020      17
6   0.408163      16
7   0.346939      15
8   0.285714      15
9   0.612245      14
10  0.571429      13
11  0.224490      13
12  0.306122      13
13  0.326531      13
14  0.632653      12
15  0.591837      12
16  0.448980      11
17  0.367347      11
18  0.693878      10
19  0.183673      10
20  0.428571      10
21  0.653061       8
22  0.387755       8
23  0.714286       7
24  0.734694       7
25  0.244898       7
26  0.142857       7
27  0.775510       6
28  0.755102       6
29  0.673469       5
30  0.204082       5
31  0.122449       5
32  0.163265       4
33  0.816327       4
34  0.877551       3
35  0.795918       3
36  0.020408       3
37  0.081633       3
38  0.836735       3
39  0.938776       2
40  0.959184       1
41  0.857143       1
42  0.000000       1
43  0.040816       1
44  0.897959       1
45  0.061224       1
46  0.102041       1
47  0.979592       1

In [8]:
#untuk mengurutkan dari Age terkecil
#dt = dt.sort_values(by=['Age'], ascending=True)
#untuk mengurukan dari jumlah terkecil
#dt = dt.sort_values(by=['Jumlah'], ascending=True)
dt.head()

        Age  Jumlah
0  0.530612      28
1  0.469388      20
2  0.265306      18
3  0.510204      18
4  0.489796      17

In [9]:
#Probabilitas
ls = []
for w in dt.Jumlah:
    x = (w + 1) / 410
    ls.append(x)
print(ls)

[0.07073170731707316, 0.05121951219512195, 0.046341463414634146, 0.046341463414634146, 0.04390243902439024, 0.04390243902439024, 0.041463414634146344, 0.03902439024390244, 0.03902439024390244, 0.036585365853658534, 0.03414634146341464, 0.03414634146341464, 0.03414634146341464, 0.03414634146341464, 0.03170731707317073, 0.03170731707317073, 0.02926829268292683, 0.02926829268292683, 0.026829268292682926, 0.026829268292682926, 0.026829268292682926, 0.02195121951219512, 0.02195121951219512, 0.01951219512195122, 0.01951219512195122, 0.01951219512195122, 0.01951219512195122, 0.01707317073170732, 0.01707317073170732, 0.014634146341463415, 0.014634146341463415, 0.014634146341463415, 0.012195121951219513, 0.012195121951219513, 0.00975609756097561, 0.00975609756097561, 0.00975609756097561, 0.00975609756097561, 0.00975609756097561, 0.007317073170731708, 0.004878048780487805, 0.004878048780487805, 0.004878048780487805, 0.004878048780487805, 0.004878048780487805, 0.004878048780487805, 0.004878048780487805, 0.004878048780487805]

In [10]:
age_ls = []; sex_ls = []; ChestPainType_ls=[]; RestingBP_ls=[]; Cholesterol_ls=[]

idx = rs_dt['Result'].values

age = idx[0]
sex = idx[1]
ChestPainType = idx[2]
RestingBP = idx[3]
Cholesterol = idx[4]
FastingBS = idx[5]
RestingECG = idx[6]
MaxHR = idx[7]
ExerciseAngina = idx[8]
Oldpeak = idx[9]
ST_Slope = idx[10]

for atx in ls:
    hs_age = age * atx
    hs_sex = sex * atx
    hs_ChestPainType = ChestPainType * atx
    hs_RestingBP = RestingBP * atx
    hs_Cholesterol = Cholesterol * atx

    age_ls.append(hs_age)
    sex_ls.append(hs_age)
    ChestPainType_ls.append(hs_ChestPainType)
    RestingBP_ls.append(hs_RestingBP)
    Cholesterol_ls.append(hs_Cholesterol)

In [11]:
data_rs = pd.DataFrame({'Age':age_ls, 'Sex':sex_ls, 'ChestPainType':ChestPainType_ls, 'RestingBP':RestingBP_ls, 'Cholesterol':ChestPainType_ls})

data_rs.head(11)

,Age,Sex,ChestPainType,RestingBP,Cholesterol
0,0.005626+0.000000j,0.005626+0.000000j,0.010584+0.000000j,0.000819+0.000000j,0.010584+0.000000j
1,0.004074+0.000000j,0.004074+0.000000j,0.007664+0.000000j,0.000593+0.000000j,0.007664+0.000000j
2,0.003686+0.000000j,0.003686+0.000000j,0.006934+0.000000j,0.000536+0.000000j,0.006934+0.000000j
3,0.003686+0.000000j,0.003686+0.000000j,0.006934+0.000000j,0.000536+0.000000j,0.006934+0.000000j
4,0.003492+0.000000j,0.003492+0.000000j,0.006569+0.000000j,0.000508+0.000000j,0.006569+0.000000j
5,0.003492+0.000000j,0.003492+0.000000j,0.006569+0.000000j,0.000508+0.000000j,0.006569+0.000000j
6,0.003298+0.000000j,0.003298+0.000000j,0.006204+0.000000j,0.000480+0.000000j,0.006204+0.000000j
7,0.003104+0.000000j,0.003104+0.000000j,0.005839+0.000000j,0.000452+0.000000j,0.005839+0.000000j
8,0.003104+0.000000j,0.003104+0.000000j,0.005839+0.000000j,0.000452+0.000000j,0.005839+0.000000j
9,0.002910+0.000000j,0.002910+0.000000j,0.005474+0.000000j,0.000423+0.000000j,0.005474+0.000000j
10,0.002716+0.000000j,0.002716+0.000000j,0.005110+0.000000j,0.000395+0.000000j,0.005110+0.000000j

In [12]:
sum_data = data_rs.sum(axis = 1)
print(sum_data)

0     0.033240+0.000000j
1     0.024070+0.000000j
2     0.021778+0.000000j
3     0.021778+0.000000j
4     0.020631+0.000000j
5     0.020631+0.000000j
6     0.019485+0.000000j
7     0.018339+0.000000j
8     0.018339+0.000000j
9     0.017193+0.000000j
10    0.016047+0.000000j
11    0.016047+0.000000j
12    0.016047+0.000000j
13    0.016047+0.000000j
14    0.014900+0.000000j
15    0.014900+0.000000j
16    0.013754+0.000000j
17    0.013754+0.000000j
18    0.012608+0.000000j
19    0.012608+0.000000j
20    0.012608+0.000000j
21    0.010316+0.000000j
22    0.010316+0.000000j
23    0.009170+0.000000j
24    0.009170+0.000000j
25    0.009170+0.000000j
26    0.009170+0.000000j
27    0.008023+0.000000j
28    0.008023+0.000000j
29    0.006877+0.000000j
30    0.006877+0.000000j
31    0.006877+0.000000j
32    0.005731+0.000000j
33    0.005731+0.000000j
34    0.004585+0.000000j
35    0.004585+0.000000j
36    0.004585+0.000000j
37    0.004585+0.000000j
38    0.004585+0.000000j
39    0.003439+0.000000j
40    0.002292+0.000000j
41    0.002292+0.000000j
42    0.002292+0.000000j
43    0.002292+0.000000j
44    0.002292+0.000000j
45    0.002292+0.000000j
46    0.002292+0.000000j
47    0.002292+0.000000j
dtype: complex128